export default {
    "Black": 'Aleo-Black',
    "BlackItalic": 'Aleo-BlackItalic',
    "Bold": 'Aleo-Bold',
    "BoldItalic": 'Aleo-BoldItalic',
    "ExtraBold": 'Aleo-ExtraBold',
    "ExtraBoldItalic": 'Aleo-ExtraBoldItalic',
    "ExtraLight": 'Aleo-ExtraLight',
    "ExtraLightItalic": 'Aleo-ExtraLightItalic',
    "Italic": 'Aleo-Italic',
    "Light": 'Aleo-Light',
    "LightItalic": 'Aleo-LightItalic',
    "Medium": 'Aleo-Medium',
    "MediumItalic": 'Aleo-MediumItalic',
    "Regular": 'Aleo-Regular',
    "SemiBold": 'Aleo-SemiBold',
    "SemiBoldItalic": 'Aleo-SemiBoldItalic',
    "Thin": 'Aleo-Thin',
    "ThinItalic": 'Aleo-ThinItalic',
};