export default {
    //Errors
    sessionExpired: "Session Expired",
    UNAUTHORIZE:"Unauthorize",
    requestTimedOut: "Request Timed Out",
    timeoutError: "The connection timed out. Please ensure you're connected to the internet and try again.",
    looksLikeYourSessionHasExpiredNoWorriesJustLogBackIn: "Looks like your session has expired. No worries, just log back in.",
    serverError: "Looks like our server is having a little hiccup. We're on it!",
    userNameNotAvailable:"This username is not available, Try a suggested username, Or enter a new one",

    // Api responses
    emailSent: "Email Sent!",
    checkYourEmailYourOtpIsOnItsWay: "Check your email! Your OTP is on its way.",
    verified: "Verified!",
    OOPS:"Oops!!",

    //Main Strings
    SKIP:'Skip',
    NEXT:'Next',
    SIGN_IN_TO_YOUR_ACCOUNT:'Sign in to your Account',
    CREATE_YOUR_ACCOUNT:'Create your account',
    ENTER_YOUR_EMAIL_ADDRESS:"Enter your email Address",
    ENTER_YOUR_EMAIL:"Enter your email",
    ENTER_YOUR_PASSWORD:"Enter your Password",
    FORGOT_PASSWORD_MARK :"Forgot Password ?",
    CONTINUE:"Continue",
    CONTINUE_WITH_GOOGLE:"Continue with Google",
    DONT_HAVE_AN_ACCOUNT:'Don’t have an account',
    ALREADY_HAVE_AN_ACCOUNT:'Already have an account? ',
    SIGNUP:"Sign up.",
    SIGNIN:"Sign in",
    SIGNIN_DOT:"Sign in.",
    OR:"OR",
    SUBMIT:"Submit",
    FORGOT_PASSWORD:"Forgot Password",
    FORGOT_PASSWORD_TEXT:"Don’t worry! it happens. Please enter the email associated with your account.",
    CREATE_PASSWORD:"Create Password",
    CREATE_PASSWORD_TEXT:"Your new password must be different from previously used passwords.",
    ENTER_NEW_PASSWORD:"Enter new password",
    SAVE_NEW_PASSWORD:"Save new password",
    CONFIRM_NEW_PASSWORD:"Confirm new password",
    PASSWORD_CHANGED_TEXT:"“Congratulations, you’ve successfully changed your password.”",
    BACK_TO_SIGNIN:"Back to Signin",
    PASSWORD_CHANGED:"Password Changed",
    CONFIRM_YOUR_ACCOUNT:"Confirm your Account",
    CONFIRM_YOUR_ACCOUNT_TEXT:"Enter the code we’ve sent via email to",
    DIDNT_GET_CODE:"Didn’t get the code ? ",
    RESEND_OTP:"Resend again",
    CREATE_PROFILE:"Create your Profile",
    UPLOAD_YOUR_PROFILE_PHOTO:"Upload your profile photo",
    UPLOAD_YOUR_COVER_PHOTO:"Upload your cover photo",
    USERNAME:"Enter Your Username",
    BIO:"Bio",
    GENDER:"Gender",
    EDUCATION:"Education",
    LOCATION:"Location",
    PROFILE_CREATED:"Profile Created",
    PROFILE_CREATED_TEXT:"“Congratulations, you’ve successfully created your profile.",
    GET_STARTED: "Get started",
    ACCEPT_AND_CONTINUE: "Accept and Continue",
    PRIVACY_POLICY:"Privacy Policy",
    TERMS_AND_CONDITION:"Terms of Service",
}